ARG V2RAY_VER SS_VER

FROM ubuntu:latest AS middle

RUN apt update && apt install -y wget xz-utils

RUN <<-EOR
    ARCH="$(uname -m)"
    case ${ARCH} in
        "aarch64") ARCH=arm64 ;;
        "x86_64") ARCH=amd64 ;;
    esac
    wget -O v2ray-plugin.tar.gz https://github.com/teddysun/v2ray-plugin/releases/download/v${V2RAY_VER}/v2ray-plugin-linux-${ARCH}-v${V2RAY_VER}.tar.gz
    tar -xf v2ray-plugin.tar.gz && rm v2ray-plugin.tar.gz
    mv v2ray-plugin_linux_${ARCH} /usr/local/bin/v2ray-plugin
EOR

FROM ghcr.io/shadowsocks/ssserver-rust:v${SS_VER} AS server

LABEL org.opencontainers.image.source="https://github.com/ResRipper/dockerfile-lib"
LABEL org.opencontainers.image.description='shadowsocks-rust + v2ray'

COPY --from=middle /usr/local/bin/v2ray-plugin /usr/local/bin/v2ray-plugin

ENTRYPOINT ssserver -s ${LISTEN} -m ${ENCRYPT} -k ${PASSWD} --plugin ${PLUGIN} --plugin-opts ${PLUGIN_OPT}
