; Copyright 2025 ResRipper.
; SPDX-License-Identifier: MIT

; Modified from:
; https://github.com/getgrav/docker-grav/blob/master/config/php-grav.ini

; Memory and execution
memory_limit = 512M
max_execution_time = 60
max_input_time = 60

; Upload limits
upload_max_filesize = 128M
post_max_size = 128M
max_file_uploads = 20

; Session settings
session.gc_maxlifetime = 1440
session.cookie_httponly = 1

; Hide deprecate message
log_errors = On
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT

; Hide PHP server
expose_php = Off

; https://github.com/docker-library/php/issues/878#issuecomment-938595965
fastcgi.logging = Off

; APCu
; https://www.php.net/manual/en/apcu.configuration.php
apc.enabled = 1
apc.shm_size = 64M
apc.enable_cli = 1

; Opcache
; https://www.php.net/manual/en/opcache.installation.php
; https://phpbenchlab.com/php-8-5-performance-optimization-complete-guide/

opcache.enable = 1
opcache.validate_timestamps = 1
opcache.memory_consumption = 512
opcache.interned_strings_buffer = 8
opcache.max_accelerated_files = 10000
opcache.revalidate_freq = 10
opcache.enable_cli=1

; JIT
opcache.jit = tracing
opcache.jit_buffer_size = 128M

