FROM rust:alpine AS ss-builder
ARG SS_VER=1.24.0
WORKDIR /build
RUN cargo install --root /build shadowsocks-rust@${SS_VER}

FROM golang:1 AS v2-builder
ARG V2RAY_VER=5.49.0

WORKDIR /build
RUN <<-EOR
    apt update && apt install -y git musl-tools bash-static
    git clone --branch=v${V2RAY_VER} https://github.com/teddysun/v2ray-plugin && cd v2ray-plugin
    LDFLAGS="-linkmode external -extldflags '-static' -X main.VERSION=v${V2RAY_VER} -s -w -buildid="
    GOPROXY=https://goproxy.cn CC=musl-gcc go build \
    -trimpath -buildmode=pie -mod=readonly \
    -ldflags "${LDFLAGS}"
EOR

FROM scratch AS server

LABEL org.opencontainers.image.source="https://github.com/ResRipper/dockerfile-lib"
LABEL org.opencontainers.image.description='shadowsocks-rust + v2ray'

COPY --from=ss-builder /build/bin/sslocal /usr/bin/sslocal
COPY --from=ss-builder /build/bin/ssmanager /usr/bin/ssmanager
COPY --from=ss-builder /build/bin/ssserver /usr/bin/ssserver
COPY --from=ss-builder /build/bin/ssservice /usr/bin/ssservice
COPY --from=ss-builder /build/bin/ssurl /usr/bin/ssurl

COPY --from=v2-builder /build/v2ray-plugin/v2ray-plugin /usr/bin/v2ray-plugin
COPY --from=v2-builder /usr/bin/bash-static /usr/bin/bash

ENTRYPOINT [ "/usr/bin/bash", "-c", "/usr/bin/ssserver -s $LISTEN -m $ENCRYPT -k $PASSWD --plugin $PLUGIN --plugin-opts $PLUGIN_OPT" ]
