ARG CADDY_VER

FROM caddy:${CADDY_VER}-builder-alpine AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare \
    --with github.com/mholt/caddy-l4

FROM caddy:${CADDY_VER}-alpine

LABEL org.opencontainers.image.source="https://github.com/ResRipper/dockerfile-lib"
LABEL org.opencontainers.image.description='Caddy with plugins built-in'

COPY --from=builder /usr/bin/caddy /usr/bin/caddy