# Copyright 2026 ResRipper.
# SPDX-License-Identifier: Apache-2.0

name: Build-scheduler

on:
    workflow_dispatch:
        inputs:
            push:
                type: boolean
                default: false
    # schedule:
    #     - cron: "0 0 1 * *"

jobs:
    # caddy-custom:
    #     uses: ./.github/workflows/caddy-custom.yml
    #     with:
    #         push: true

    # grav:
    #     uses: ./.github/workflows/grav.yml
    #     with:
    #         push: true

    builder:
        strategy:
            fail-fast: true
            matrix:
                include:
                    -   image: shadowsocks-rust
                        tag: 1.24.0
                        build_args: |
                            SS_VER=1.24.0
                            V2RAY_VER=5.49.0
        uses: ./.github/workflows/builder.yml
        secrets: inherit
        with:
            image: ${{ matrix.image }}
            tag: ${{ matrix.tag }}
            build_args: ${{ matrix.build_args }}
            push: ${{ inputs.push == true }}

    read_output:
        runs-on: ubuntu-latest
        needs: [builder]
        steps:
            -   uses: cloudposse/github-action-matrix-outputs-read@v1
                id: build_output
                with:
                    matrix-step-name: build
        outputs:
            result: ${{ steps.build_output.outputs.result }}

    scanner:
        needs: [read_output]
        strategy:
            fail-fast: true
            matrix:
                image: ${{ needs.read_output.outputs.result.image.* }}
        uses: ./.github/workflows/scanner.yml
        with:
            image: ${{ matrix.image }}