# Copyright 2026 ResRipper.
# SPDX-License-Identifier: Apache-2.0

name: Build scheduler

on:
    workflow_dispatch:
    schedule:
        - cron: 0 0 * * 5

jobs:
    builder:
        strategy:
            fail-fast: true
            matrix:
                platform:
                    -   linux/amd64,linux/arm64
                image: [
                    caddy-custom,
                    grav,
                    shadowsocks-rust
                ]

        runs-on: ubuntu-slim
        steps:
            -   name: Builder trigger
                run: gh workflow run -R resripper/dockerfile-lib ${{ matrix.image }}.yml -f push=true -f scan=true
                env:
                    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}