# Copyright 2026 ResRipper.
# SPDX-License-Identifier: Apache-2.0

name: CI - Caddy-custom

on:
    push:
        paths:
            - caddy-custom/dockerfile
            - .github/workflows/caddy-custom.yml
    workflow_dispatch:
        inputs:
            push:
                description: Push image to registry
                type: boolean
                default: false
            scan:
                description: Scan image for vulnerabilities
                type: boolean
                default: false

jobs:
    build-slim:
        uses: ./.github/workflows/builder.yml
        secrets: inherit
        with:
            image: caddy-custom
            tag: 2.11.4
            build_args: |
                IMAGE_BASE=scratch
                CADDY_VER=2.11.4
                MOD_CF=0.2.4
                MOD_DOCKER_PROXY=2.12.1
            push: ${{ inputs.push == true }}
            scan: ${{ inputs.scan == true }}

    build-alpine:
        uses: ./.github/workflows/builder.yml
        secrets: inherit
        with:
            image: caddy-custom
            tag: 2.11.4-alpine
            build_args: |
                IMAGE_BASE=alpine:latest
                CADDY_VER=2.11.4
                MOD_CF=0.2.4
                MOD_DOCKER_PROXY=2.12.1
            push: ${{ inputs.push == true }}
            scan: ${{ inputs.scan == true }}