name: Grav

on:
    push:
        paths:
            - content/grav/**
            - .github/workflows/grav.yml
    workflow_dispatch:

env:
    ALPINE_VER: 3.22.1
    GRAV_VER: 1.7.49.4

jobs:
    grav:
        runs-on: ubuntu-latest
        steps: [
            {
                name: Fetch repo,
                uses: actions/checkout@v4,
                with: {
                    token: "${{ secrets.PAT }}"
                }
            },
            {
                name: "Login to Docker Hub",
                uses: docker/login-action@v3,
                with: {
                    username: "${{ secrets.DOCKERHUB_USERNAME }}",
                    password: "${{ secrets.DOCKERHUB_TOKEN }}"
                }
            },
            {
                name: "Setup QEMU",
                uses: docker/setup-qemu-action@v3
            },
            {
                name: "Setup Buildx",
                uses: docker/setup-buildx-action@v3
            },
            {
                name: "Build image and publish",
                uses: docker/build-push-action@v6,
                with: {
                    context: content/grav,
                    file: content/grav/grav.dockerfile,
                    platforms: "linux/amd64,linux/arm64",
                    push: true,
                    tags: "resripper/grav:${{ env.GRAV_VER }},resripper/grav:latest",
                    cache-from: type=gha,
                    cache-to: "type=gha,mode=max",
                    build-args: "ALPINE_VER=${{ env.ALPINE_VER }}\nGRAV_VER=${{ env.GRAV_VER }}"
                }
            }
        ]