# Copyright 2026 ResRipper.
# SPDX-License-Identifier: Apache-2.0

name: CI - Grav

on:
    push:
        paths:
            - grav/**
            - .github/workflows/grav.yml
    workflow_dispatch:
        inputs:
            push:
                description: Push image to registry
                type: boolean
                default: false
            scan:
                description: Scan image for vulnerabilities
                type: boolean
                default: false

jobs:
    build:
        uses: ./.github/workflows/builder.yml
        secrets: inherit
        with:
            image: grav
            tag: 1.7.52
            build_args: |
                ALPINE_VER=latest
                GRAV_VER=1.7.52
            push: ${{ inputs.push == true }}
            scan: ${{ inputs.scan == true }}