name: Pico-SDK

on:
  push:
    paths:
      - "development/hardware/pico-sdk/dockerfile"
      - ".github/workflows/pico-sdk.yml"
  workflow_dispatch:

env:
  SDK_VER: 2.1.1

jobs:
    pico-sdk:
        runs-on: ubuntu-24.04
        permissions:
            packages: write

        steps:
            - name: Fetch repo
              uses: actions/checkout@v4
              with:
                token: ${{ secrets.PAT }}
            
            # - name: Login to Github
            #   uses: docker/login-action@v3
            #   with:
            #       registry: ghcr.io
            #       username: ${{ github.actor }}
            #       password: ${{ secrets.GITHUB_TOKEN }}

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Setup QEMU
              uses: docker/setup-qemu-action@v3

            - name: Setup Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build image and publish
              uses: docker/build-push-action@v6
              with:
                context: development/hardware/pico-sdk/
                file: development/hardware/pico-sdk/dockerfile
                platforms: linux/amd64,linux/arm64
                push: true
                tags: resripper/pico-sdk:${{env.SDK_VER}}, resripper/pico-sdk:latest
                cache-from: type=gha
                cache-to: type=gha,mode=max