# Copyright 2026 ResRipper.
# SPDX-License-Identifier: Apache-2.0

name: CI - Shadowsocks-rust

on:
    push:
        paths:
            - shadowsocks-rust/dockerfile
            - .github/workflows/shadowsocks-rust.yml
    workflow_dispatch:
        inputs:
            push:
                description: Push image to registry
                required: true
                type: boolean
                default: false
            scan:
                description: Scan image for vulnerabilities
                required: true
                type: boolean
                default: false

jobs:
    build:
        uses: ./.github/workflows/builder.yml
        secrets: inherit
        with:
            image: shadowsocks-rust
            tag: 1.24.0
            build_args: |
                SS_VER=1.24.0
                V2RAY_VER=5.49.0
            push: ${{ inputs.push == true }}
            scan: ${{ inputs.scan == true }}